version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.8.5
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Test
          command: |
            docker build .
            echo "hello2"% 
