version: 2.1
workflows:
  testing:
    jobs:
      - runner
jobs:
  runner:
    machine: true
    resource_class: owenjoliver/aws
    steps:
      - run: echo "Hi I'm on Runners!"
      - run: sleep 5m
      