version: 2.1

jobs:
  emoji:
    docker:
      - image: cimg/base:stable
    resource_class: owenjoliver/ec2_mac
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

workflows:
  ci:
    jobs:
      - emoji:
          name: "Emoji"
